
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://krkewftqqnwhzjgqppcr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtya2V3ZnRxcW53aHpqZ3FwcGNyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDczMjkxNjksImV4cCI6MjA2MjkwNTE2OX0.IelJBlmrk8798oLZFYSb3JhO6WcyM_nVqmgXHzH2XGM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
